export const survivorPerks = [
    {
        name: "Bond",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/bond.png",
        teachable: "Dwight Fairfield Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/01-dwight-fairfield.png",
      },
      {
        name: "Prove Thyself",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/prove-thyself.png",
        teachable: "Dwight Fairfield Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/01-dwight-fairfield.png",
      },
      {
        name: "Leader",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/leader.png",
        teachable: "Dwight Fairfield Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/01-dwight-fairfield.png",
      },
      {
        name: "Quick and Quiet",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/quick-and-quiet.png",
        teachable: "Meg Thomas Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/02-meg-thomas.png",
      },
      {
        name: "Sprint Burst",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/sprint-burst.png",
        teachable: "Meg Thomas Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/02-meg-thomas.png",
      },
      {
        name: "Adrenaline",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/adrenaline.png",
        teachable: "Meg Thomas Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/02-meg-thomas.png",
    },
    {
        name: "Empathy",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/empathy.png",
        teachable: "Claudette Morel Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/03-claudette-morel.png",
      },
      {
        name: "Botany Knowledge",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/botany-knowledge.png",
        teachable: "Claudette Morel Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/03-claudette-morel.png",
      },
      {
        name: "Self-Care",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/self-care.png",
        teachable: "Claudette Morel Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/03-claudette-morel.png",
      },
      {
        name: "Iron Will",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/iron-will.png",
        teachable: "Jake Park Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/04-jake-park.png",
      },
      {
        name: "Calm Spirit",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/calm-spirit.png",
        teachable: "Jake Park Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/04-jake-park.png",
      },
      {
        name: "Saboteur",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/saboteur.png",
        teachable: "Jake Park Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/04-jake-park.png",
      },
      {
        name: "Balanced Landing",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/balanced-landing.png",
        teachable: "Nea Karlsson Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/05-nea-karlsson.png",
      },
      {
        name: "Urban Evasion",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/urban-evasion.png",
        teachable: "Nea Karlsson Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/05-nea-karlsson.png",
      },
      {
        name: "Streetwise",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/streetwise.png",
        teachable: "Nea Karlsson Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/05-nea-karlsson.png",
      },
      {
        name: "Sole Survivor",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/sole-survivor.png",
        teachable: "Laurie Strode Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/08-laurie-strode.png",
      },
      {
        name: "Object of Obsession",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/object-of-obsession.png",
        teachable: "Laurie Strode Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/08-laurie-strode.png",
      },
      {
        name: "Decisive Strike",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/decisive-strike.png",
        teachable: "Laurie Strode Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/08-laurie-strode.png",
      },
      {
        name: "Open Handed",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/open-handed.png",
        teachable: "Ace Visconti Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/09-ace-visconti.png",
      },
      {
        name: "Up the Ante",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/up-the-ante.png",
        teachable: "Ace Visconti Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/09-ace-visconti.png",
      },
      {
        name: "Ace in the Hole",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/ace-in-the-hole.png",
        teachable: "Ace Visconti Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/09-ace-visconti.png",
    },
]