export const survivorPerks = [
    {
        name: "Bond",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/bond.png",
        teachable: "Dwight Fairfield Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/01-dwight-fairfield.png",
      },
      {
        name: "Prove Thyself",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/prove-thyself.png",
        teachable: "Dwight Fairfield Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/01-dwight-fairfield.png",
      },
      {
        name: "Leader",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/leader.png",
        teachable: "Dwight Fairfield Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/01-dwight-fairfield.png",
      },
      {
        name: "Quick and Quiet",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/quick-and-quiet.png",
        teachable: "Meg Thomas Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/02-meg-thomas.png",
      },
      {
        name: "Sprint Burst",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/sprint-burst.png",
        teachable: "Meg Thomas Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/02-meg-thomas.png",
      },
      {
        name: "Adrenaline",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/adrenaline.png",
        teachable: "Meg Thomas Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/02-meg-thomas.png",
    },
    {
        name: "Empathy",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/empathy.png",
        teachable: "Claudette Morel Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/03-claudette-morel.png",
      },
      {
        name: "Botany Knowledge",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/botany-knowledge.png",
        teachable: "Claudette Morel Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/03-claudette-morel.png",
      },
      {
        name: "Self-Care",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/self-care.png",
        teachable: "Claudette Morel Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/03-claudette-morel.png",
      },
      {
        name: "Iron Will",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/iron-will.png",
        teachable: "Jake Park Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/04-jake-park.png",
      },
      {
        name: "Calm Spirit",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/calm-spirit.png",
        teachable: "Jake Park Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/04-jake-park.png",
      },
      {
        name: "Saboteur",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/saboteur.png",
        teachable: "Jake Park Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/04-jake-park.png",
      },
      {
        name: "Balanced Landing",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/balanced-landing.png",
        teachable: "Nea Karlsson Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/05-nea-karlsson.png",
      },
      {
        name: "Urban Evasion",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/urban-evasion.png",
        teachable: "Nea Karlsson Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/05-nea-karlsson.png",
      },
      {
        name: "Streetwise",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/streetwise.png",
        teachable: "Nea Karlsson Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/05-nea-karlsson.png",
      },
      {
        name: "Sole Survivor",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/sole-survivor.png",
        teachable: "Laurie Strode Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/08-laurie-strode.png",
      },
      {
        name: "Object of Obsession",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/object-of-obsession.png",
        teachable: "Laurie Strode Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/08-laurie-strode.png",
      },
      {
        name: "Decisive Strike",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/decisive-strike.png",
        teachable: "Laurie Strode Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/08-laurie-strode.png",
      },
      {
        name: "Open Handed",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/open-handed.png",
        teachable: "Ace Visconti Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/09-ace-visconti.png",
      },
      {
        name: "Up the Ante",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/up-the-ante.png",
        teachable: "Ace Visconti Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/09-ace-visconti.png",
      },
      {
        name: "Ace in the Hole",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/ace-in-the-hole.png",
        teachable: "Ace Visconti Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/09-ace-visconti.png",
    },
    {
        name: "Left Behind",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/left-behind.png",
        teachable: 'William "Bill" Overbeck Teachable Perk',
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/06-bill-overbeck.png",
      },
      {
        name: "Borrowed Time",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/borrowed-time.png",
        teachable: 'William "Bill" Overbeck Teachable Perk',
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/06-bill-overbeck.png",
      },
      {
        name: "Unbreakable",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/unbreakable.png",
        teachable: 'William "Bill" Overbeck Teachable Perk',
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/06-bill-overbeck.png",
      },
      {
        name: "Technician",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/technician.png",
        teachable: "Feng Min Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/10-feng-min.png",
      },
      {
        name: "Lithe",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/lithe.png",
        teachable: "Feng Min Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/10-feng-min.png",
      },
      {
        name: "Alert",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/alert.png",
        teachable: "Feng Min Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/10-feng-min.png",
    },
    {
        name: "We're Gonna Live Forever",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/were-gonna-live-forever.png",
        teachable: "David King Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/07-david-king.png",
      },
      {
        name: "Dead Hard",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/dead-hard.png",
        teachable: "David King Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/07-david-king.png",
      },
      {
        name: "No Mither",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/no-mither.png",
        teachable: "David King Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/07-david-king.png",
      },
      {
        name: "Wake Up",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/wake-up.png",
        teachable: "Quentin Smith Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/11-quentin-smith.png",
      },
      {
        name: "Pharmacy",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/pharmacy.png",
        teachable: "Quentin Smith Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/11-quentin-smith.png",
      },
      {
        name: "Vigil",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/vigil.png",
        teachable: "Quentin Smith Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/11-quentin-smith.png",
      },
      {
        name: "Tenacity",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/tenacity.png",
        teachable: "Detective David Tapp Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/12-detective-david-tapp.png",
      },
      {
        name: "Detectives Hunch",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/detectives-hunch.png",
        teachable: "Detective David Tapp Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/12-detective-david-tapp.png",
      },
      {
        name: "Stake Out",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/stakeout.png",
        teachable: "Detective David Tapp Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/12-detective-david-tapp.png",
      },
      {
        name: "Dance With Me",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/dance-with-me.png",
        teachable: "Kate Denson Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/13-kate-denson.png",
      },
      {
        name: "Windows of Opportunity",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/windows-of-opportunity.png",
        teachable: "Kate Denson Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/13-kate-denson.png",
      },
      {
        name: "Boil Over",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/boil-over.png",
        teachable: "Kate Denson Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/13-kate-denson.png",
      },
      {
        name: "Diversion",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/diversion.png",
        teachable: "Adam Francis Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/14-adam-francis.png",
      },
      {
        name: "Deliverance",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/deliverance.png",
        teachable: "Adam Francis Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/14-adam-francis.png",
      },
      {
        name: "Autodidact",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/autodidact.png",
        teachable: "Adam Francis Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/14-adam-francis.png",
      },
      {
        name: "Breakdown",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/breakdown.png",
        teachable: "Jeff Johansen Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/15-jeff-johansen.png",
      },
      {
        name: "After Care",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/after-care.png",
        teachable: "Jeff Johansen Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/15-jeff-johansen.png",
    },
    {
        name: "Distortion",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/distortion.png",
        teachable: "Jeff Johansen Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/15-jeff-johansen.png",
    },
    {
        name: "Solidarity",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/solidarity.png",
        teachable: "Jane Romero Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/16-jane-romero.png",
    },
    {
        name: "Poised",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/poised.png",
        teachable: "Jane Romero Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/16-jane-romero.png",
      },
      {
        name: "Head On",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/head-on.png",
        teachable: "Jane Romero Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/16-jane-romero.png",
      },
      {
        name: "Flip-Flop",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/flip-flop.png",
        teachable: "Ashley J. Williams Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/17-ash-williams.png",
      },
      {
        name: "Buckle Up",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/buckle-up.png",
        teachable: "Ashley J. Williams Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/17-ash-williams.png",
      },
      {
        name: "Mettle of Man",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/mettle-of-man.png",
        teachable: "Ashley J. Williams Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/17-ash-williams.png",
      },
      {
        name: "Situational Awareness",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/better-together.png",
        teachable: "Nancy Wheeler Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/18-nancy-wheeler.png",
      },
      {
        name: "Self-Aware",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/fixated.png",
        teachable: "Nancy Wheeler Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/18-nancy-wheeler.png",
      },
      {
        name: "Inner Healing",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/inner-strength.png",
        teachable: "Nancy Wheeler Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/18-nancy-wheeler.png",
      },
      {
        name: "Guardian",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/babysitter.png",
        teachable: "Steve Harrington Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/19-steve-harrington.png",
      },
      {
        name: "Kinship",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/camaraderie.png",
        teachable: "Steve Harrington Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/19-steve-harrington.png",
      },
      {
        name: "Renewal",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/renewal.png",
        teachable: "Steve Harrington Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/19-steve-harrington.png",
      },
      {
        name: "Lucky Break",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/lucky-break.png",
        teachable: "Yui Kimura Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/20-yui-kimura.png",
      },
      {
        name: "Any Means Necessary",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/any-means-necessary.png",
        teachable: "Yui Kimura Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/20-yui-kimura.png",
    },
    {
        name: "Breakout",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/survivor-perks/breakout.png",
        teachable: "Yui Kimura Teachable Perk",
        survivor: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/survivors/20-yui-kimura.png",
      },

]