export const killerPerks = [
    {
        name: "Unnerving Presence",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/unnerving-presence.png",
        teachable: "The Trapper Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/01-the-trapper.png",
    },
    {
        name: "Brtual Strength",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/brutal-strength.png",
        teachable: "The Trapper Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/01-the-trapper.png",
    },
    {
        name: "Agitation",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/agitation.png",
        teachable: "The Trapper Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/01-the-trapper.png",
    },
    {
        name: "Predator",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/predator.png",
        teachable: "The Wraith Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/02-the-wraith.png",
    },
    {
        name: "Bloodhound",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/bloodhound.png",
        teachable: "The Wraith Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/02-the-wraith.png",
    },
    {
        name: "Shadowborn",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/shadowborn.png",
        teachable: "The Wraith Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/02-the-wraith.png",
    },
    {
        name: "Enduring",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/enduring.png",
        teachable: "The Hillbilly Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/03-the-hillbilly.png",
    },
    {
        name: "Lightborn",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/lightborn.png",
        teachable: "The Hillbilly Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/03-the-hillbilly.png",
    },
    {
        name: "Tinkerer",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/tinkerer.png",
        teachable: "The Hillbilly Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/03-the-hillbilly.png",
    },
    {
        name: "Stridor",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/stridor.png",
        teachable: "The Nurse Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/04-the-nurse.png",
    },
    {
        name: "Thanatophobia",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/thanatophobia.png",
        teachable: "The Nurse Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/04-the-nurse.png",
    },
    {
        name: "A Nurse's Calling",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/a-nurses-calling.png",
        teachable: "The Nurse Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/04-the-nurse.png",
    },
    {
        name: "Save the Best for Last",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/save-the-best-for-last.png",
        teachable: "The Shape Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/05-the-shape.png",
    },
    {
        name: "Play with Your Food",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/play-with-your-food.png",
        teachable: "The Shape Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/05-the-shape.png",
    },
    {
        name: "Dying Light",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/dying-light.png",
        teachable: "The Shape Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/05-the-shape.png",
    },
    {
        name: "Hex: The Third Seal",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/hex-the-third-seal.png",
        teachable: "The Hag Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/06-the-hag.png",
    },
    {
        name: "Hex: Ruin",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/hex-ruin.png",
        teachable: "The Hag Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/06-the-hag.png",
    },
    {
        name: "Hex: Devour Hope",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/hex-devour-hope.png",
        teachable: "The Hag Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/06-the-hag.png",
    },
    {
        name: "Overwhelming Presence",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/overwhelming-presence.png",
        teachable: "The Doctor Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/07-the-doctor.png",
    },
    {
        name: "Monitor & Abuse",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/monitor-and-abuse.png",
        teachable: "The Doctor Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/07-the-doctor.png",
    },
    {
        name: "Overcharge",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/overcharge.png",
        teachable: "The Doctor Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/07-the-doctor.png",
    },
    {
        name: "Beast of Prey",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/beast-of-prey.png",
        teachable: "The Huntress Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/08-the-huntress.png",
    },
    {
        name: "Territorial Imperative",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/territorial-imperative.png",
        teachable: "The Huntress Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/08-the-huntress.png",
    },
    {
        name: "Hex: Huntress Lullaby",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/hex-huntress-lullaby.png",
        teachable: "The Huntress Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/08-the-huntress.png",
    },
    {
        name: "Knock Out",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/knock-out.png",
        teachable: "The Cannibal Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/09-the-cannibal.png",
    },
    {
        name: "Barbecue & Chilli",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/barbecue-and-chilli.png",
        teachable: "The Cannibal Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/09-the-cannibal.png",
    },
    {
        name: "Franklin's Demise",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/franklins-demise.png",
        teachable: "The Cannibal Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/09-the-cannibal.png",
    },
    {
        name: "Fire Up",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/fire-up.png",
        teachable: "The Nightmare Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/10-the-nightmare.png",
    },
    {
        name: "Remember Me",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/remember-me.png",
        teachable: "The Nightmare Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/10-the-nightmare.png",
    },
    {
        name: "Blood Warden",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/blood-warden.png",
        teachable: "The Nightmare Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/10-the-nightmare.png",
    },
    {
        name: "Hangman's Trick",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/hangmans-trick.png",
        teachable: "The Pig Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/11-the-pig.png",
    },
    {
        name: "Surveillance",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/surveillance.png",
        teachable: "The Pig Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/11-the-pig.png",
    },
    {
        name: "Make Your Choice",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/make-your-choice.png",
        teachable: "The Pig Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/11-the-pig.png",
    },
    {
        name: "Bamboozle",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/bamboozle.png",
        teachable: "The Clown Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/12-the-clown.png",
    },
    {
        name: "Coulrophobia",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/coulrophobia.png",
        teachable: "The Clown Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/12-the-clown.png",
    },
    {
        name: "Pop Goes the Weasel",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/pop-goes-the-weasel.png",
        teachable: "The Clown Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/12-the-clown.png",
    },
    {
        name: "Spirit Fury",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/spirit-fury.png",
        teachable: "The Spirit Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/13-the-spirit.png",
    },
    {
        name: "Hex: Haunted Ground",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/hex-haunted-ground.png",
        teachable: "The Spirit Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/13-the-spirit.png",
    },
    {
        name: "Rancor",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/rancor.png",
        teachable: "The Spirit Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/13-the-spirit.png",
    },
    {
        name: "Discordance",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/discordance.png",
        teachable: "The Legion Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/14-the-legion.png",
    },
    {
        name: "Mad Grit",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/mad-grit.png",
        teachable: "The Legion Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/14-the-legion.png",
    },
    {
        name: "Iron Maiden",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/iron-maiden.png",
        teachable: "The Legion Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/14-the-legion.png",
    },
    {
        name: "Corrupt Intervention",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/corrupt-intervention.png",
        teachable: "The Plague Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/15-the-plague.png",
    },
    {
        name: "Infectious Fright",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/infectious-fright.png",
        teachable: "The Plague Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/15-the-plague.png",
    },
    {
        name: "Dark Devotion",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/dark-devotion.png",
        teachable: "The Plague Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/15-the-plague.png",
    },
    {
        name: "I'm All Ears",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/im-all-ears.png",
        teachable: "The Ghost Face Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/16-the-ghost-face.png",
    },
    {
        name: "Thrilling Tremors",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/thrilling-tremors.png",
        teachable: "The Ghost Face Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/16-the-ghost-face.png",
    },
    {
        name: "Furtive Chase",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/furtive-chase.png",
        teachable: "The Ghost Face Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/16-the-ghost-face.png",
    },
    {
        name: "Jolt",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/jolt.png",
        teachable: "The Demogorgon Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/17-the-demogorgon.png",
    },
    {
        name: "Claustrophobia",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/claustrophobia.png",
        teachable: "The Demogorgon Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/17-the-demogorgon.png",
    },
    {
        name: "Fearmonger",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/fearmonger.png",
        teachable: "The Demogorgon Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/17-the-demogorgon.png",
    },
    {
        name: "Zanshin Tactics",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/zanshin-tactics.png",
        teachable: "The Oni Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/18-the-oni.png",
    },
    {
        name: "Blood Echo",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/blood-echo.png",
        teachable: "The Oni Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/18-the-oni.png",
    },
    {
        name: "Nemesis",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/nemesis.png",
        teachable: "The Oni Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/18-the-oni.png",
    },
    {
        name: "Gearhead",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/gearhead.png",
        teachable: "The Deathslinger Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/19-the-deathslinger.png",
    },
    {
        name: "Dead Man's Switch",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/dead-mans-switch.png",
        teachable: "The Deathslinger Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/19-the-deathslinger.png",
    },
    {
        name: "Hex: Retribution",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/hex-retribution.png",
        teachable: "The Deathslinger Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/19-the-deathslinger.png",
    },
    {
        name: "Forced Penance",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/forced-penance.png",
        teachable: "The Executioner Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/20-the-executioner.png",
    },
    {
        name: "Trail of Torment",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/trail-of-torment.png",
        teachable: "The Executioner Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/20-the-executioner.png",
    },
    {
        name: "Deathbound",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/deathbound.png",
        teachable: "The Executioner Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/20-the-executioner.png",
    },
    {
        name: "Dragon's Grip",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/dragons-grip.png",
        teachable: "The Blight Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/21-the-blight.png",
    },
    {
        name: "Hex: Blood Favour",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/hex-blood-favour.png",
        teachable: "The Blight Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/21-the-blight.png",
    },
    {
        name: "Hex: Undying",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/hex-undying.png",
        teachable: "The Blight Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/21-the-blight.png",
    },
    {
        name: "Hoarder",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/hoarder.png",
        teachable: "The Twins Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/22-the-twins.png",
    },
    {
        name: "Oppression",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/oppression.png",
        teachable: "The Twins Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/22-the-twins.png",
    },
    {
        name: "Coup de Grâce",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/coup-de-grace.png",
        teachable: "The Twins Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/22-the-twins.png",
    },
    {
        name: "Starstruck",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/starstruck.png",
        teachable: "The Trickster Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/23-the-trickster.png",
    },
    {
        name: "Hex: Crowd Control",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/hex-crowd-control.png",
        teachable: "The Trickster Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/23-the-trickster.png",
    },
    {
        name: "No Way Out",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/no-way-out.png",
        teachable: "The Trickster Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/23-the-trickster.png",
    },
    {
        name: "Lethal Pursuer",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/lethal-pursuer.png",
        teachable: "The Nemesis Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/24-the-nemesis.png",
    },
    {
        name: "Hysteria",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/hysteria.png",
        teachable: "The Nemesis Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/24-the-nemesis.png",
    },
    {
        name: "Eruption",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/eruption.png",
        teachable: "The Nemesis Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/24-the-nemesis.png",
    },
    {
        name: "Deadlock",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/deadlock.png",
        teachable: "The Cenobite Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/25-the-cenobite.png",
    },
    {
        name: "Hex: Plaything",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/hex-plaything.png",
        teachable: "The Cenobite Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/25-the-cenobite.png",
    },
    {
        name: "Scourge Hook: Gift of Pain",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/scourge-hook-gift-of-pain.png",
        teachable: "The Cenobite Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/25-the-cenobite.png",
    },
    {
        name: "Grim Embrace",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/grim-embrace.png",
        teachable: "The Artist Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/26-the-artist.png",
    },
    {
        name: "Scourge Hook: Pain Resonance",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/scourge-hook-pain-resonance.png",
        teachable: "The Artist Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/26-the-artist.png",
    },
    {
        name: "Hex: Pentimento",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/hex-pentimento.png",
        teachable: "The Artist Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/26-the-artist.png",
    },
    {
        name: "Scourge Hook: Floods of Rage",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/scourge-hook-floods-of-rage.png",
        teachable: "The Onryō Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/27-the-onryo.png",
    },
    {
        name: "Call of Brine",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/call-of-brine.png",
        teachable: "The Onryō Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/27-the-onryo.png",
    },
    {
        name: "Merciless Storm",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/merciless-storm.png",
        teachable: "The Onryō Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/27-the-onryo.png",
    },
    {
        name: "Dissolution",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/dissolution.png",
        teachable: "The Dredge Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/28-the-dredge.png",
    },
    {
        name: "Darkness Revealed",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/darkness-revealed.png",
        teachable: "The Dredge Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/28-the-dredge.png",
    },
    {
        name: "Septic Touch",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/septic-touch.png",
        teachable: "The Dredge Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/28-the-dredge.png",
    },

    // **************************************
    // GENERAL KILLER PERKS SECTION
    // **************************************

    {
        name: "Bitter Murmur",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/bitter-murmur.png",
        teachable: "All Killers",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/00-all-killers.png",
    },
    {
        name: "Deerstalker",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/deerstalker.png",
        teachable: "All Killers",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/00-all-killers.png",
    },
    {
        name: "Distressing",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/distressing.png",
        teachable: "All Killers",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/00-all-killers.png",
    },
    {
        name: "Hex: No One Escapes Death",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/hex-no-one-escapes-death.png",
        teachable: "All Killers",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/00-all-killers.png",
    },
    {
        name: "Hex: Thrill of the Hunt",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/hex-thrill-of-the-hunt.png",
        teachable: "All Killers",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/00-all-killers.png",
    },
    {
        name: "Insidious",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/insidious.png",
        teachable: "All Killers",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/00-all-killers.png",
    },
    {
        name: "Iron Grasp",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/iron-grasp.png",
        teachable: "All Killers",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/00-all-killers.png",
    },
    {
        name: "Scourge Hook: Monstrous Shrine",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/monstrous-shrine.png",
        teachable: "All Killers",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/00-all-killers.png",
    },
    {
        name: "Shattered Hope",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/shattered-hope.png",
        teachable: "All Killers",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/00-all-killers.png",
    },
    {
        name: "Sloppy Butcher",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/sloppy-butcher.png",
        teachable: "All Killers",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/00-all-killers.png",
    },
    {
        name: "Spies from the Shadows",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/spies-from-the-shadows.png",
        teachable: "All Killers",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/00-all-killers.png",
    },
    {
        name: "Unrelenting",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/unrelenting.png",
        teachable: "All Killers",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/00-all-killers.png",
    },
    {
        name: "Whispers",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/whispers.png",
        teachable: "All Killers",
        killer: "https://raw.githubusercontent.com/joeytierney/dbd-vue/develop/src/assets/character-portraits/killers/00-all-killers.png",
    },
]