export const killerPerks = [
    {
        name: "Unnerving Presence",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/unnerving-presence.png",
        teachable: "The Trapper Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/killers/01-the-trapper.png",
    },
    {
        name: "Brtual Strength",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/brutal-strength.png",
        teachable: "The Trapper Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/killers/01-the-trapper.png",
    },
    {
        name: "Agitation",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/agitation.png",
        teachable: "The Trapper Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/killers/01-the-trapper.png",
    },
    {
        name: "Predator",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/predator.png",
        teachable: "The Wraith Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/killers/02-the-wraith.png",
    },
    {
        name: "Bloodhound",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/bloodhound.png",
        teachable: "The Wraith Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/killers/02-the-wraith.png",
    },
    {
        name: "Shadowborn",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/shadowborn.png",
        teachable: "The Wraith Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/killers/02-the-wraith.png",
    },
    {
        name: "Enduring",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/enduring.png",
        teachable: "The Hillbilly Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/killers/03-the-hillbilly.png",
    },
    {
        name: "Lightborn",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/lightborn.png",
        teachable: "The Hillbilly Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/killers/03-the-hillbilly.png",
    },
    {
        name: "Tinkerer",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/tinkerer.png",
        teachable: "The Hillbilly Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/killers/03-the-hillbilly.png",
    },
    {
        name: "Stridor",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/stridor.png",
        teachable: "The Nurse Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/killers/04-the-nurse.png",
    },
    {
        name: "Thanatophobia",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/thanatophobia.png",
        teachable: "The Nurse Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/killers/04-the-nurse.png",
    },
    {
        name: "A Nurse's Calling",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/a-nurses-calling.png",
        teachable: "The Nurse Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/killers/04-the-nurse.png",
    },
    {
        name: "Save the Best for Last",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/save-the-best-for-last.png",
        teachable: "The Shape Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/killers/05-the-shape.png",
    },
    {
        name: "Play with Your Food",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/play-with-your-food.png",
        teachable: "The Shape Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/killers/05-the-shape.png",
    },
    {
        name: "Dying Light",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/dying-light.png",
        teachable: "The Shape Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/killers/05-the-shape.png",
    },
    {
        name: "Hex: The Third Seal",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/hex-the-third-seal.png",
        teachable: "The Hag Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/killers/06-the-hag.png",
    },
    {
        name: "Hex: Ruin",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/hex-ruin.png",
        teachable: "The Hag Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/killers/06-the-hag.png",
    },
    {
        name: "Hex: Devour Hope",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/hex-devour-hope.png",
        teachable: "The Hag Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/killers/06-the-hag.png",
    },
    {
        name: "Overwhelming Presence",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/overwhelming-presence.png",
        teachable: "The Doctor Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/killers/07-the-doctor.png",
    },
    {
        name: "Monitor & Abuse",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/monitor-and-abuse.png",
        teachable: "The Doctor Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/killers/07-the-doctor.png",
    },
    {
        name: "Overcharge",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/overcharge.png",
        teachable: "The Doctor Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/killers/07-the-doctor.png",
    },
    {
        name: "Beast of Prey",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/beast-of-prey.png",
        teachable: "The Huntress Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/killers/08-the-huntress.png",
    },
    {
        name: "Territorial Imperative",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/territorial-imperative.png",
        teachable: "The Huntress Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/killers/08-the-huntress.png",
    },
    {
        name: "Hex: Huntress Lullaby",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/hex-huntress-lullaby.png",
        teachable: "The Huntress Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/killers/08-the-huntress.png",
    },
    {
        name: "Knock Out",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/knock-out.png",
        teachable: "The Cannibal Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/killers/09-the-cannibal.png",
    },
    {
        name: "Barbecue & Chilli",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/barbecue-and-chilli.png",
        teachable: "The Cannibal Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/killers/09-the-cannibal.png",
    },
    {
        name: "Franklin's Demise",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/franklins-demise.png",
        teachable: "The Cannibal Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/killers/09-the-cannibal.png",
    },
    {
        name: "Fire Up",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/fire-up.png",
        teachable: "The Nightmare Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/killers/10-the-nightmare.png",
    },
    {
        name: "Remember Me",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/remember-me.png",
        teachable: "The Nightmare Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/killers/10-the-nightmare.png",
    },
    {
        name: "Blood Warden",
        image: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/perks/killer-perks/blood-warden.png",
        teachable: "The Nightmare Teachable Perk",
        killer: "https://raw.githubusercontent.com/joeytierney/deadbydaylight-randomizer/main/public/assets/character-portraits/killers/10-the-nightmare.png",
    },
]