<template>
  <br />
  <h1>Privacy Policy</h1>
  <h2>Google Analytics</h2>
  <p>
    <span>
      This website uses Google Analytics, a web analytics service from Google
      Inc. ("Google").
    </span>
    <br /><br />
    Google Analytics uses "Cookies". Cookies are text files that are stored on
    the computer of the visitor and which enable an analysis of the use of the
    website. The information about the website use by the visitor generated by
    the cookie is transmitted to Google and is stored on Google servers in the
    USA. This information contains the truncated IP address of the visitor.
    <br /><br />
    On behalf of the site operator, Google will use the information collected to
    evaluate the use of the website, to compile reports on website activities
    and to provide further services to the site operator in connection with the
    use of the website and the internet. The legitimate interest in the data
    processing lies in the optimisation of this website, the analysis of the use
    of the website and the adaptation of the contents.
    <br /><br />
    Google is subject to the Privacy Shield Agreement. The collected data
    through Google Analytics is automatically deleted after 14 months. Data
    whose retention period has been reached is automatically deleted once a
    month.<br /><br />The visitor can deny the collection and storage of his
    information through a browser plugin provided by Google that can be
    downloaded and installed on this website:
    <a
      class="link"
      target="_blank"
      href="https://tools.google.com/dlpage/gaoptout"
      >https://tools.google.com/dlpage/gaoptout</a
    >. <br /><br />
    Further information on the use of data by Google and how to prevent the
    collection and usage of your information can be found in the privacy policy
    of Google (<a
      class="link"
      target="_blank"
      href="https://policies.google.com/privacy"
      >https://policies.google.com/privacy</a
    >).
  </p>
</template>
